// apps/examples/svelte/src/lib/ImageZoom.svelte
<script>
import mediumZoom from 'medium-zoom';

export const src = undefined;
export const alt = undefined;
export const options = undefined;

let zoom = null;

function getZoom() {
	if (zoom === null) {
		zoom = mediumZoom(options);
	}

	return zoom;
}

function attachZoom(image) {
	const zoom = getZoom();
	zoom.attach(image);

	return {
		update(newOptions) {
			zoom.update(newOptions);
		},
		destroy() {
			zoom.detach();
		},
	};
}
</script>

<img {src} {alt} {...$$restProps} use:attachZoom={options} />

// apps/examples/react/src/ImageZoom.tsx
import { useRef, type ComponentProps, type RefCallback } from 'react';
import mediumZoom, { type Zoom, type ZoomOptions } from 'medium-zoom';

type ImageZoomProps = ComponentProps<'img'> & {
	options?: ZoomOptions;
};

export function ImageZoom({ options, ...props }: ImageZoomProps) {
	const zoomRef = useRef<Zoom | null>(null);

	function getZoom() {
		if (zoomRef.current === null) {
			zoomRef.current = mediumZoom(options);
		}

		return zoomRef.current;
	}

	const attachZoom: RefCallback<HTMLImageElement> = (node) => {
		const zoom = getZoom();

		if (node) {
			zoom.attach(node);
		} else {
			zoom.detach();
		}
	};

	return <img {...props} ref={attachZoom} />;
}
